# Generated by Django 6.0.5 on 2026-05-23 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp')], default='whatsapp', max_length=20)),
                ('recipient_type', models.CharField(choices=[('customer', 'Customer'), ('technician', 'Technician'), ('manager', 'Manager')], max_length=20)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('deep_link_url', models.TextField()),
                ('notification_status', models.CharField(choices=[('generated', 'Generated'), ('sent', 'Sent')], default='generated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
